# Windowrules customised accordingly
windowrule = opacity 1 override, match:class ^vlc$
windowrule = opacity 1 override, match:class ^(jetbrains-studio|jetbrains-idea-ce)$
windowrule = opacity 1, match:class ^firefox$
windowrule = rounding 3, match:class ^firefox$
windowrule = workspace 3 silent, match:class ^vesktop$
windowrule = workspace 4 silent, match:class ^(io.github.kukuruzka165.materialgram|zapzap)$
windowrule = float on, match:class ^(com.github.neithern.g4music|org.qbittorrent.qBittorrent)$
windowrule = float on, match:class ^it.mijorus.smile$
windowrule = float on, match:class ^xdg-desktop-portal-gtk$
windowrule = stay_focused on, match:class ^pinentry-

# Picture-in-Picture special treatment
windowrule = float on, match:title ^Picture in picture$
windowrule = size 585 330, match:title ^Picture in picture$
windowrule = move 100%-816 50, match:title ^Picture in picture$
windowrule = pin on, match:title ^Picture in picture$
windowrule = no_dim on, match:title ^Picture in picture$
windowrule = opacity 1 0.8, match:title ^Picture in picture$
windowrule = no_initial_focus on, match:title ^Picture in picture$
