# waybar
layerrule = blur on, match:namespace waybar
layerrule = ignore_alpha 0.1, match:namespace waybar
layerrule = blur_popups on, match:namespace waybar

# logout_dialog
layerrule = blur on, match:namespace logout_dialog
layerrule = animation popin 95%, match:namespace logout_dialog

# rofi
layerrule = blur on, match:namespace rofi
layerrule = ignore_alpha 0.1, match:namespace rofi
layerrule = animation popin 95%, match:namespace rofi

# swaync-control-center
layerrule = blur on, match:namespace swaync-control-center
layerrule = ignore_alpha 0.1, match:namespace swaync-control-center
layerrule = animation popin 95%, match:namespace swaync-control-center

# swaync-notification-window
layerrule = blur on, match:namespace swaync-notification-window
layerrule = ignore_alpha 0.1, match:namespace swaync-notification-window
layerrule = animation slide, match:namespace swaync-notification-window
